name: Publish package to NPM

on:
  push:
    tags:
      - 'js-lib-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: './dist/package.json'
          token: ${{ secrets.NPM_TOKEN }}
